FROM python:3.9

# Install ssh
RUN apt-get update && apt-get install -y openssh-client

# Set environment
ENV PYTHONUNBUFFERED 1

# Work spaces
WORKDIR /app

# Copy environment
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install -r requirements.txt

# Copy
COPY  . /app

# Ssart SSH tunel
CMD python manage.py runserver 0.0.0.0:8000
